### ISSUE TITLE
application.yml에 spring.security.oauth2.redirect_url 설정값 누락

### ISSUE THREAD

**Issue by sirzzang** [bsideproject/team4-backend#25]
- #23 PR에 `application.yml`에 설정되어야 하는 `redirect_uri` 설정값 누락
- 어플리케이션 시작 시 `IllegalArgumentException` 발생

**Comment by sirzzang** [comment]
@zoey-lee-korea 주혜님 제가 PR 검토 후 close할 때 해당 설정값이 없다는 것을 놓친 채 머지해버렸습니다. `develop` 브랜치 기준 PR 머지 후의 `application.yml` 설정 파일에 `redirect_uri` 값이 없는 거 같은데 확인 부탁드릴게요 🙏

**Comment by zoey-lee-korea** [comment]
- spring.security.oauth2.redirect_url 설정값 추가해서 바로 develop에 반영해 놨습니다!
- 어플리케이션 시작 시 IllegalArgumentException 발생하는지 확인 부탁드립니다

**Comment by sirzzang** [comment]
해결되었습니다! 감사합니다 🙏
