### ISSUE TITLE
회원 및 가족 repository 메서드 변경 확인 요청

### ISSUE THREAD

**Issue by sirzzang** [bsideproject/team4-backend#32]
@zoey-lee-korea 님, #31 확인 후 시큐리티 서비스 내에서 영향 받는 로직 있다면 변경해주시면 감사하겠습니다!

+ `FindByProviderAndProviderId`와 `FindByUsername` 메서드 두 개가 어차피 식별하고자 하는 레코드가 동일하기 때문에, 하나 삭제하려 하는데, 시큐리티 쪽 회원 관련 로직에 영향이 있을 거 같아서요. 어떤 메서드 삭제하는 게 더 괜찮으실 지도 댓글 달아 주시면 감사하겠습니다!

**Comment by zoey-lee-korea** [comment]
token에 `username` 을 넣어놨고, token을 열어볼 때도 `FindByUsername` 을 사용하고 있어서
`FindByProviderAndProviderId` 를 삭제하는게 나을거 같습니다!

**Comment by sirzzang** [comment]
넵 감사합니다!
