### ISSUE TITLE
펫 도메인 엔티티 구현 확인 요청

### ISSUE THREAD

**Issue by sirzzang** [bsideproject/team4-backend#35]
@zoey-lee-korea 님, 펫 도메인 엔티티 구현했습니다. 

#34 에서 펫 도메인 엔티티 확인 가능 후, 스케쥴, 퀵 기록 API 구현에서 펫 id 관련되어 변경해야 하는 부분 변경해주시면 됩니다🙏

해당 내용 변경 시, 펫 도메인에서 수정되어야 하는 부분(예컨대, 펫 도메인과 스케쥴과의 객체 관계 설정 등) 댓글로 알려 주시면 엔티티 코드 변경해 두겠습니다. 변경해 보다가 펫 도메인 이상한 부분 있으면 알려 주세요!

**Comment by zoey-lee-korea** [comment]
네 알겠습니다!!
그럼 `User` 엔티티에서 main_pet_id는 `pet` 엔티티로 변경되는 걸까요??
전에 main_pet_id를 Long타입으로 가져갈거라고도 했던거 같아서요..!

**Comment by sirzzang** [comment]
아마 바뀔 수도 있을 거 같아요! 근데 대표펫 관련 기능 구현하다 보니까 쪼끔 고민해야 할 지점이 있는 거 같아서 지금 시점에서는 정확하게 답변을 드리지 못하겠네요ㅠㅠ 오늘 회의 전에 대표펫 관련 내용 구현해 두고 주혜님 리뷰 요청드리겠습니다!
