### ISSUE TITLE
대표펫 설정 관련 유저 도메인 엔티티 구현 확인 요청

### ISSUE THREAD

**Issue by sirzzang** [bsideproject/team4-backend#38]
@zoey-lee-korea 주혜님, 대표펫 설정 관련해서 일단은 1마리만 설정할 수 있도록 해 두었습니다.

- `main_pet_id`가 지금 `String` 타입인데, `Long` 타입으로 변경 예정입니다. 주혜님 관련 부분 변경 후 PR 생성해 주시면, 펫 서비스 내에서 변경해야 할 부분 변경하겠습니다.
- 아마 현재 `UserRepository` 및 `PetRepository`에 `main_pet_id`로 사용자 및 회원 찾는 메서드가 없습니다. 만약 해당 메서드 필요하다면, `mainPetId` 파라미터 타입만 `Long`으로 변경된 부분 확인 후 알맞는 메서드 생성해 두도록 하겠습니다!

**Comment by zoey-lee-korea** [comment]
### 이전의 다른 질문 (#37)
이 PR이랑 크게 관계는 없긴 한데.. security config에서 그룹장 권한 필요하다고 설정한 url에 /api/v1이 안 들어가도록 하고 싶은데.. 혹시 **로 해도 괜찮을까요?
### 답변
네 저도 security config에서 /api/v1이 들어있는걸 방금 깨달았네요..ㅎㅎ 
**로 작업하셔도 될 거 같습니다!

**Comment by zoey-lee-korea** [comment]
네 퀵기록, 일정을 남길 때 Pet 정보를 Pet 객체로 저장하려고 합니다!

`main_pet_id` 먼저 `Long`타입으로 변경해 주실 수 있으실까요??
제가 먼저 수정하려해도 에러 메시지가 뜨긴 해서요...
![image](https://user-images.githubusercontent.com/68551829/189088994-e737db8f-e963-43cf-8d50-4bd6016be950.png)

펫을 조회할 때는 위처럼, JWT토큰의 `User`에서 `getMainPetId()`로 대표펫Id를 불러온 뒤, `petRepository`에서 `findByPetId`를 사용하려 했습니다
.
.
정리하자면
- `main_pet_id`만 `Long`으로 변경해 주시면 되고,
- `Long` 변경 후 퀵기록/일정에서도 관련 수정 진행하기?!
- Pet 조회를 위해 `User`의 `getMainPetId()`는 그대로 유지! 해 주시면 될 거 같습니다!

**Comment by sirzzang** [comment]
넵 mainPetId 변경해두도록 하겠습니다!

**Comment by sirzzang** [comment]
@zoey-lee-korea 주혜님 `mainPetId` 속성 타입 변경 관련 PR #47 에서 반영해 두었습니다!

**Comment by zoey-lee-korea** [comment]
네 확인했습니다! `mainPetId` 관련 변경 작업 시작하겠습니다!
