### ISSUE TITLE
JwtAuthorizationFilter 예외 처리 요청

### ISSUE THREAD

**Issue by sirzzang** [bsideproject/team4-backend#64]
@zoey-lee-korea 주혜님 security 관련 서버 에러가 발생하여 예외 처리 요청 드립니다~

- `JwtAuthorizationFilter.java` 82번째 줄 `findByUsername` 없을 때 500에러 발생
- `UserNotFoundException` 예외 처리 변경 필요

**Comment by zoey-lee-korea** [comment]
네 Issue 확인했습니다! 확인해 보고 작업해 두도록 하겠습니다!

**Comment by sirzzang** [comment]
#67 확인 후 머지했습니다~
