### ISSUE TITLE
config.properties cannot opened 오류 발생

### ISSUE THREAD

**Issue by sirzzang** [bsideproject/team4-backend#74]
- #71 머지 이후 `FileNotFoundException` 에러 발생하며 어플리케이션 실행되지 않고 종료
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/58291139/194301796-36f4fa28-108f-4afc-aa15-9b566c46ce76.png">

**Comment by sirzzang** [comment]
@zoey-lee-korea  주혜님 제가 PR 리뷰 시 코드만 보고 실행시켜보지 못했더니 위와 같은 오류가 발생하는 상황을 인지하지 못한 채 머지를 했습니다. 죄송해요ㅠ 혹시 위 오류 어떻게 해결하면 좋을지 아시나요?

**Comment by zoey-lee-korea** [comment]
제가 `config.properties`를 push를 안 해 놨었네요 ㅠ 서버에는 따로 추가해 놨긴 한데... 에러가 발생하니 일단 config.properties 파일을 push하도록 하겠습니다!

**Comment by sirzzang** [comment]
#78에서 해결
